"""
Native C++ backend for A11
"""

from __future__ import annotations
import a11.status
import a11.stores.local_chunk_store
import asyncio
import fastapi
import httpx
import collections.abc
import msgpack._cmsgpack
import typing

T = typing.TypeVar("T")

class _DoneEvent(typing.Protocol):
    def is_set(self) -> bool: ...
    async def wait(self) -> bool: ...

__all__: list[str] = [
    "ACCEPT",
    "ACTION_DISPATCH_STATUS_OUTPUT",
    "ACTION_HEADER_PREFIX",
    "ACTION_STATUS_MIMETYPE",
    "ACTION_STATUS_OUTPUT",
    "Action",
    "ActionHeaderSchema",
    "ActionMessage",
    "ActionPortSchema",
    "ActionRegistry",
    "ActionSchema",
    "ActionSettings",
    "AsyncNode",
    "CANCEL_ACTION_HEADER",
    "CANCEL_ACTION_NAME",
    "CANDIDATE",
    "ChannelFramingOptions",
    "Chunk",
    "ChunkMetadata",
    "ChunkStore",
    "ChunkStoreReader",
    "ChunkStoreReaderOptions",
    "ChunkStoreWriter",
    "ChunkStoreWriterOptions",
    "DEFAULT_MAX_CONCURRENT_NESTED_ACTIONS",
    "DEFAULT_SSE_CONNECT_ENDPOINT",
    "DEFAULT_SSE_MESSAGE_ENDPOINT",
    "DESCRIPTION",
    "Duration",
    "EMPTY_WIRE_MESSAGE_SIZE",
    "ERROR",
    "Http2Client",
    "Http2DuplexStream",
    "Http2Options",
    "Http2RequestBodyStream",
    "Http2ResponseStream",
    "Http2ResponseWriter",
    "Http2Server",
    "Http2TlsOptions",
    "HttpRequest",
    "HttpResponse",
    "HttpResponseHead",
    "HttpSseClientWireStream",
    "HttpSseOptions",
    "HttpSseServer",
    "HttpSseServerWireStream",
    "HttpSseWireStream",
    "HttpSseWireStreamServer",
    "InProcessWireStream",
    "JSON_MIMETYPE",
    "LocalChunkStore",
    "MAX_SINGLE_MESSAGE_SIZE",
    "MSGPACK_MIMETYPE",
    "NodeFragment",
    "NodeMap",
    "NodeRef",
    "Port",
    "SESSION_MAX_SINGLE_MESSAGE_SIZE",
    "SESSION_STATUS_HEADER",
    "SSE_HTTP_HEADER_PREFIX",
    "SSE_STREAM_ID_HEADER",
    "START",
    "SerializationRegistry",
    "Session",
    "SessionOptions",
    "SessionWithRecv",
    "SignallingEndpoint",
    "SignallingMessage",
    "SignallingMessageType",
    "SignallingService",
    "SignallingTransport",
    "Status",
    "StreamMode",
    "TCP",
    "TLS",
    "Time",
    "TurnRelayType",
    "TurnServer",
    "UDP",
    "WHOLE_JSON",
    "WIRE_MESSAGE_VERSION",
    "WIRE_STREAM_ABORT_STATUS_HEADER",
    "WIRE_STREAM_MAX_SINGLE_MESSAGE_SIZE",
    "WebRtcConfiguration",
    "WebRtcWireServer",
    "WebRtcWireStream",
    "WebSocketClientOptions",
    "WebSocketServerOptions",
    "WebSocketSignallingClient",
    "WebSocketSignallingClientOptions",
    "WebSocketSignallingServer",
    "WebSocketSignallingServerOptions",
    "WebSocketWireServer",
    "WebSocketWireStream",
    "WireMessage",
    "WireStream",
    "WireStreamOptions",
    "WireStreamWithRecv",
    "create_in_process_wire_stream_pair",
    "get_http_header",
    "is_half_close_message",
    "is_status_chunk",
    "make_half_close_message",
    "normalize_session_headers",
    "status_code_from_http",
    "status_code_from_websocket",
    "status_code_to_http",
    "status_code_to_websocket",
    "status_from_chunk",
    "status_to_chunk",
    "validate_http_headers",
    "validate_name_string",
]

class Action:
    id: str
    schema: ActionSchema
    settings: ActionSettings
    def __await__(self): ...
    def get_header(
        self, name: str, decode: bool = False
    ) -> bytes | str | None: ...
    @staticmethod
    def make_node_id(arg0: str, arg1: str) -> str: ...
    @staticmethod
    def run_in_background(*args, **kwargs):
        """
        run(self: Action) -> Action
        """

    def __contains__(self, arg0: str) -> bool: ...
    def __getitem__(self, arg0: str) -> AsyncNode: ...
    def __init__(
        self,
        schema: ActionSchema,
        action_id: str = "",
        handler: typing.Any | None = None,
        *,
        node_map: NodeMap | None = None,
        stream: WireStream | None = None,
        session: Session | None = None,
        registry: ActionRegistry | None = None,
        max_concurrent_nested_actions: typing.SupportsInt = 64,
    ) -> None: ...
    def bind_handler(self, arg0: typing.Any) -> Action: ...
    def bind_node_map(self, arg0: NodeMap) -> Action: ...
    def bind_registry(self, arg0: ActionRegistry) -> Action: ...
    def bind_session(self, arg0: Session) -> Action: ...
    def bind_stream(self, arg0: WireStream) -> Action: ...
    def bind_streams_on_inputs_by_default(self, arg0: bool) -> Action: ...
    def bind_streams_on_outputs_by_default(self, arg0: bool) -> Action: ...
    def call(self, wire_headers: typing.Any | None = None) -> typing.Any: ...
    def cancel(self) -> None: ...
    def cancelled(self) -> bool: ...
    def clear_inputs_after_run(self, clear: bool = True) -> Action: ...
    def clear_outputs_after_run(self, clear: bool = True) -> Action: ...
    def contains_port(self, arg0: str) -> bool: ...
    def forward_header(self, arg0: Action, arg1: str) -> None: ...
    def forward_headers_with_prefix(
        self, target: Action, prefix: str = "x-a11-"
    ) -> None: ...
    def get_action_message(self) -> ActionMessage: ...
    def get_dispatch_status(self) -> typing.Any: ...
    def get_handler(self) -> typing.Any: ...
    def get_id(self) -> str: ...
    def get_input(
        self, name: str, bind_stream: bool | None = None
    ) -> AsyncNode: ...
    def get_node(self, arg0: str) -> AsyncNode: ...
    def get_node_map(self) -> NodeMap: ...
    def get_output(
        self, name: str, bind_stream: bool | None = None
    ) -> AsyncNode: ...
    def get_port(self, arg0: str) -> AsyncNode: ...
    def get_registry(self) -> ActionRegistry: ...
    def get_schema(self) -> ActionSchema: ...
    def get_session(self) -> Session: ...
    def get_status(self) -> typing.Any: ...
    def get_stream(self) -> WireStream: ...
    def has_been_called(self) -> bool: ...
    def has_been_run(self) -> bool: ...
    def has_handler(self) -> bool: ...
    def has_header(self, arg0: str) -> bool: ...
    def is_done(self) -> bool: ...

    @typing.overload
    def make_nested(
        self,
        schema: ActionSchema,
        propagate_io: bool = True,
        forward_headers: bool = True,
    ) -> Action: ...
    @typing.overload
    def make_nested(
        self,
        action_name: str,
        propagate_io: bool = True,
        forward_headers: bool = True,
    ) -> Action: ...

    def map_ports_from_message(self, arg0: ActionMessage) -> Action: ...
    def remove_header(self, arg0: str) -> None: ...
    def run(self) -> Action: ...
    def set_header(self, arg0: str, arg1: typing.Any) -> Action: ...
    def set_id(self, arg0: str) -> Action: ...
    def set_on_cancelled(self, arg0: typing.Any) -> None: ...
    def set_schema(self, arg0: ActionSchema) -> Action: ...
    def wait(self, timeout: typing.Any | None = None) -> typing.Any: ...
    def wait_for_dispatch(
        self, timeout: typing.Any | None = None
    ) -> typing.Any: ...
    @property
    def done(self) -> _DoneEvent: ...
    @property
    def headers(self) -> dict: ...

class ActionHeaderSchema:
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    default: typing.Any
    description: str
    name: str
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler): ...
    @classmethod
    def __get_pydantic_json_schema__(cls, _schema, _handler): ...
    @classmethod
    def model_json_schema(cls, **_: typing.Any) -> dict[str, typing.Any]: ...
    @classmethod
    def model_validate(cls, value: typing.Any, **_: typing.Any): ...
    @classmethod
    def model_validate_json(cls, value: str | bytes, **_: typing.Any): ...
    def __eq__(self, arg0: object) -> bool: ...
    def __init__(
        self,
        name: str,
        description: str = "",
        default: typing.Any | None = None,
    ) -> None: ...
    def model_copy(
        self,
        *,
        update: collections.abc.Mapping[str, typing.Any] | None = None,
        deep: bool = False,
    ): ...
    def model_dump(self, *, mode: str = "python", **_: typing.Any): ...
    def model_dump_json(self, **kwargs: typing.Any) -> str: ...
    def validate(self) -> None: ...

class ActionMessage:
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    id: str
    name: str
    @staticmethod
    def from_msgpack(data: typing.Any) -> ActionMessage: ...
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler): ...
    @classmethod
    def __get_pydantic_json_schema__(cls, _schema, _handler): ...
    @classmethod
    def model_construct(cls, **values: typing.Any):
        """
        Construct a native value from trusted field values.

            Native records retain C++ invariants. This validates input rather than
            creating an invalid object.

        """

    @classmethod
    def model_json_schema(cls, **_: typing.Any) -> dict[str, typing.Any]: ...
    @classmethod
    def model_validate(cls, value: typing.Any, **_: typing.Any): ...
    @classmethod
    def model_validate_json(
        cls, value: str | bytes | bytearray, **_: typing.Any
    ): ...
    def __copy__(self) -> ActionMessage: ...
    def __deepcopy__(self, memo: dict) -> ActionMessage: ...
    def __eq__(self, arg0: object) -> bool: ...
    def __init__(
        self,
        id: str = "",
        name: str = "",
        inputs: typing.Any = [],
        outputs: typing.Any = [],
        headers: typing.Any = {},
    ) -> None: ...
    def __repr__(self) -> str: ...
    def debug_string(self) -> str: ...
    def model_copy(
        self, *, update: dict[str, typing.Any] | None = None, deep: bool = False
    ): ...
    def model_dump(
        self, *, mode: str = "python", **_: typing.Any
    ) -> dict[str, typing.Any]: ...
    def model_dump_json(self, **kwargs: typing.Any) -> str: ...
    def to_msgpack(self) -> bytes: ...
    def validate(self) -> None: ...
    @property
    def approx_bytes(self) -> int: ...

    @property
    def headers(self) -> _ByteMapView: ...
    @headers.setter
    def headers(self, arg1: typing.Any) -> None: ...

    @property
    def inputs(self) -> _PortVectorView: ...
    @inputs.setter
    def inputs(self, arg1: typing.Any) -> None: ...

    @property
    def outputs(self) -> _PortVectorView: ...
    @outputs.setter
    def outputs(self, arg1: typing.Any) -> None: ...

class ActionPortSchema:
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    autofills: typing.Any
    description: str
    name: str
    required: bool
    type: str
    unary: bool
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler): ...
    @classmethod
    def __get_pydantic_json_schema__(cls, _schema, _handler): ...
    @classmethod
    def model_json_schema(cls, **_: typing.Any) -> dict[str, typing.Any]: ...
    @classmethod
    def model_validate(cls, value: typing.Any, **_: typing.Any): ...
    @classmethod
    def model_validate_json(cls, value: str | bytes, **_: typing.Any): ...
    def __eq__(self, arg0: object) -> bool: ...
    def __init__(
        self,
        name: str,
        type: str,
        description: str = "",
        required: bool = False,
        unary: bool = False,
        autofills: typing.Any | None = None,
    ) -> None: ...
    def model_copy(
        self,
        *,
        update: collections.abc.Mapping[str, typing.Any] | None = None,
        deep: bool = False,
    ): ...
    def model_dump(self, *, mode: str = "python", **_: typing.Any): ...
    def model_dump_json(self, **kwargs: typing.Any) -> str: ...
    def validate(self) -> None: ...

class ActionRegistry:
    def __init__(self) -> None: ...
    def copy(self, clear_autofills: bool = True) -> ActionRegistry: ...
    def get_handler(self, arg0: str) -> typing.Any: ...
    def get_schema(self, arg0: str) -> ActionSchema: ...
    def is_registered(self, arg0: str) -> bool: ...
    def list_registered_actions(self) -> list[str]: ...
    def make_action(
        self,
        action_name: str,
        action_id: str = "",
        node_map: NodeMap | None = None,
        stream: WireStream | None = None,
        session: Session | None = None,
    ) -> Action: ...
    def make_action_message(
        self, action_name: str, action_id: str = ""
    ) -> ActionMessage: ...
    def register(
        self,
        action_name: str,
        schema: ActionSchema,
        handler: typing.Any | None = None,
    ) -> None: ...
    def register_sync(
        self, action_name: str, schema: ActionSchema, handler: typing.Any
    ) -> None: ...
    def unregister(self, arg0: str) -> None: ...

class ActionSchema:
    WHOLE_JSON: typing.ClassVar[str] = "$"
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    description: str
    name: str
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler): ...
    @classmethod
    def __get_pydantic_json_schema__(cls, _schema, _handler): ...
    @classmethod
    def model_json_schema(cls, **_: typing.Any) -> dict[str, typing.Any]: ...
    @classmethod
    def model_validate(cls, value: typing.Any, **_: typing.Any): ...
    @classmethod
    def model_validate_json(cls, value: str | bytes, **_: typing.Any): ...
    def __eq__(self, arg0: object) -> bool: ...
    def __init__(
        self,
        name: str,
        description: str = "",
        inputs: typing.Any = {},
        outputs: typing.Any = {},
        headers: typing.Any = {},
        output_to_json_field: collections.abc.Mapping[str, str] = {},
    ) -> None: ...
    def map_output_to_json(
        self, output_name: str, field_name: str = ""
    ) -> None: ...
    def model_copy(
        self,
        *,
        update: collections.abc.Mapping[str, typing.Any] | None = None,
        deep: bool = False,
    ): ...
    def model_dump(self, *, mode: str = "python", **_: typing.Any): ...
    def model_dump_json(self, **kwargs: typing.Any) -> str: ...
    def validate(self) -> None: ...

    @property
    def headers(self) -> _ActionHeaderSchemaMapView: ...
    @headers.setter
    def headers(self, arg1: typing.Any) -> None: ...

    @property
    def inputs(self) -> _ActionPortSchemaMapView: ...
    @inputs.setter
    def inputs(self, arg1: typing.Any) -> None: ...

    @property
    def output_to_json_field(self) -> _StringSchemaMapView: ...
    @output_to_json_field.setter
    def output_to_json_field(
        self, arg1: collections.abc.Mapping[str, str]
    ) -> None: ...

    @property
    def outputs(self) -> _ActionPortSchemaMapView: ...
    @outputs.setter
    def outputs(self, arg1: typing.Any) -> None: ...

class ActionSettings:
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    bind_streams_on_inputs_by_default: typing.Any
    bind_streams_on_outputs_by_default: typing.Any
    clear_inputs_after_run: typing.Any
    clear_outputs_after_run: typing.Any
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler): ...
    @classmethod
    def __get_pydantic_json_schema__(cls, _schema, _handler): ...
    @classmethod
    def model_json_schema(cls, **_: typing.Any) -> dict[str, typing.Any]: ...
    @classmethod
    def model_validate(cls, value: typing.Any, **_: typing.Any): ...
    @classmethod
    def model_validate_json(cls, value: str | bytes, **_: typing.Any): ...
    def __eq__(self, arg0: object) -> bool: ...
    def __init__(
        self,
        bind_streams_on_inputs_by_default: bool | None = None,
        bind_streams_on_outputs_by_default: bool | None = None,
        clear_inputs_after_run: bool = False,
        clear_outputs_after_run: bool = False,
    ) -> None: ...
    def model_copy(
        self,
        *,
        update: collections.abc.Mapping[str, typing.Any] | None = None,
        deep: bool = False,
    ): ...
    def model_dump(self, *, mode: str = "python", **_: typing.Any): ...
    def model_dump_json(self, **kwargs: typing.Any) -> str: ...

class AsyncNode:
    reader_options: ChunkStoreReaderOptions
    serialization_registry: SerializationRegistry
    writer_options: ChunkStoreWriterOptions
    async def __aenter__(self) -> AsyncNode: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: typing.Any,
    ) -> None: ...
    def __aiter__(self) -> AsyncNode: ...
    async def __anext__(self) -> typing.Any: ...
    def __init__(
        self,
        chunk_store: ChunkStore,
        node_map: NodeMap | None = None,
        *,
        serialization_registry: SerializationRegistry | None = None,
        reader_options: (
            ChunkStoreReaderOptions | dict[str, typing.Any] | None
        ) = None,
        writer_options: (
            ChunkStoreWriterOptions | dict[str, typing.Any] | None
        ) = None,
    ) -> None: ...
    @staticmethod
    def _validate_expected_types(
        mimetype_patterns: str | typing.Sequence[str], obj_type: type | None
    ) -> str | tuple[str, ...]: ...
    async def consume(
        self,
        obj_type: type[T] | None = None,
        timeout: Duration | None = None,
        mimetype_patterns: str | typing.Sequence[str] = "",
    ) -> T | typing.Any: ...
    async def consume_chunk(self, timeout: Duration | None = None) -> Chunk: ...
    async def consume_fragment(
        self, timeout: Duration | None = None
    ) -> NodeFragment: ...
    def expect_types(self, **kwds) -> typing.Iterator[AsyncNode]: ...
    def get_reader_options(self) -> ChunkStoreReaderOptions: ...
    def get_writer_options(self) -> ChunkStoreWriterOptions: ...
    def iter_chunks(
        self, timeout: Duration | None = None
    ) -> collections.abc.AsyncIterator[Chunk]: ...
    def iter_fragments(
        self, timeout: Duration | None = None
    ) -> collections.abc.AsyncIterator[NodeFragment]: ...
    async def next(
        self,
        obj_type: type[T] | None = None,
        timeout: Duration | None = None,
        mimetype_patterns: str | typing.Sequence[str] = "",
    ) -> T | typing.Any | None: ...
    async def next_chunk(
        self, timeout: Duration | None = None
    ) -> Chunk | None: ...
    async def next_fragment(
        self, timeout: Duration | None = None
    ) -> NodeFragment | None: ...
    async def next_object(
        self,
        obj_type: type[T] | None = None,
        timeout: Duration | None = None,
        mimetype_patterns: str | typing.Sequence[str] = "",
    ) -> T | typing.Any | None: ...
    async def put(
        self,
        value: typing.Any,
        seq: int | None = None,
        final: bool = False,
        mimetype: str = "",
    ) -> asyncio.Future[int]: ...
    async def put_chunk(
        self, chunk: Chunk, seq: int | None = None, final: bool = False
    ) -> asyncio.Future[int]:
        """
        Enqueue a native chunk and return its durable confirmation future.
        """

    async def put_final(
        self, value: typing.Any, seq: int | None = None, mimetype: str = ""
    ) -> asyncio.Future[int]: ...
    async def put_fragment(
        self, fragment: NodeFragment
    ) -> asyncio.Future[int]: ...
    async def put_null_final(
        self, seq: int | None = None
    ) -> asyncio.Future[int]: ...
    def reset_reader(
        self,
        options: ChunkStoreReaderOptions | dict[str, typing.Any] | None = None,
    ) -> AsyncNode: ...
    def set_expected_types(
        self,
        mimetype_patterns: str | typing.Sequence[str],
        obj_type: type | None,
    ) -> AsyncNode: ...
    def set_reader_options(
        self, options: ChunkStoreReaderOptions | dict[str, typing.Any]
    ) -> AsyncNode: ...
    def set_serialization_registry(
        self, registry: SerializationRegistry
    ) -> AsyncNode: ...
    def set_writer_options(
        self, options: ChunkStoreWriterOptions | dict[str, typing.Any]
    ) -> AsyncNode: ...
    @classmethod
    def create(
        cls: type[AsyncNode],
        node_id: str,
        node_map: NodeMap | None = None,
        *,
        serialization_registry: SerializationRegistry | None = None,
        reader_options: (
            ChunkStoreReaderOptions | dict[str, typing.Any] | None
        ) = None,
        writer_options: (
            ChunkStoreWriterOptions | dict[str, typing.Any] | None
        ) = None,
        chunk_store_factory: typing.Callable[
            [str], ChunkStore
        ] = a11.stores.local_chunk_store.LocalChunkStore,
    ) -> AsyncNode: ...
    def abort_with_status(self, arg0: typing.Any) -> typing.Any: ...
    def attach_stream(self, arg0: WireStream) -> None: ...
    def cancel(self) -> None: ...
    def cancel_reader(self) -> None: ...
    def cancel_writer(self) -> None: ...
    def detach_stream(self, arg0: WireStream) -> None: ...
    def drain_and_close(self) -> typing.Any: ...
    def get_chunk_store(self) -> ChunkStore: ...
    def get_id(self) -> str: ...
    def get_reader_status(self) -> typing.Any: ...
    def get_writer_abort_status(self) -> typing.Any: ...
    def get_writer_status(self) -> typing.Any: ...
    def is_writable(self) -> typing.Any: ...
    def wait_for_buffer_to_drain(self) -> typing.Any: ...
    @property
    def chunk_store(self) -> ChunkStore: ...
    @property
    def id(self) -> str: ...
    @property
    def reader(self) -> ChunkStoreReader: ...
    @property
    def writer(self) -> ChunkStoreWriter: ...

class ChannelFramingOptions:
    def __init__(self) -> None: ...
    def validate(self) -> None: ...

    @property
    def max_pending_bytes(self) -> int: ...
    @max_pending_bytes.setter
    def max_pending_bytes(self, arg0: typing.SupportsInt) -> None: ...

    @property
    def max_pending_messages(self) -> int: ...
    @max_pending_messages.setter
    def max_pending_messages(self, arg0: typing.SupportsInt) -> None: ...

    @property
    def split_size(self) -> int: ...
    @split_size.setter
    def split_size(self, arg0: typing.SupportsInt) -> None: ...

class Chunk:
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    metadata: typing.Any
    ref: str
    @staticmethod
    def from_msgpack(data: typing.Any) -> Chunk: ...
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler): ...
    @classmethod
    def __get_pydantic_json_schema__(cls, _schema, _handler): ...
    @classmethod
    def model_construct(cls, **values: typing.Any):
        """
        Construct a native value from trusted field values.

            Native records retain C++ invariants. This validates input rather than
            creating an invalid object.

        """

    @classmethod
    def model_json_schema(cls, **_: typing.Any) -> dict[str, typing.Any]: ...
    @classmethod
    def model_validate(cls, value: typing.Any, **_: typing.Any): ...
    @classmethod
    def model_validate_json(
        cls, value: str | bytes | bytearray, **_: typing.Any
    ): ...
    def __copy__(self) -> Chunk: ...
    def __deepcopy__(self, memo: dict) -> Chunk: ...
    def __eq__(self, arg0: object) -> bool: ...
    def __init__(
        self,
        metadata: typing.Any | None = None,
        ref: str = "",
        data: typing.Any = b"",
    ) -> None: ...
    def __repr__(self) -> str: ...
    def debug_string(self) -> str: ...
    def get_mimetype(self) -> str: ...
    def is_empty(self) -> bool: ...
    def is_null(self) -> bool: ...
    def model_copy(
        self, *, update: dict[str, typing.Any] | None = None, deep: bool = False
    ): ...
    def model_dump(
        self, *, mode: str = "python", **_: typing.Any
    ) -> dict[str, typing.Any]: ...
    def model_dump_json(self, **kwargs: typing.Any) -> str: ...
    def to_msgpack(self) -> bytes: ...
    def validate(self) -> None: ...
    @property
    def approx_bytes(self) -> int: ...

    @property
    def data(self) -> bytes: ...
    @data.setter
    def data(self, arg1: typing.Any) -> None: ...

class ChunkMetadata:
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    mimetype: str
    timestamp: typing.Any
    @staticmethod
    def from_msgpack(data: typing.Any) -> ChunkMetadata: ...
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler): ...
    @classmethod
    def __get_pydantic_json_schema__(cls, _schema, _handler): ...
    @classmethod
    def model_construct(cls, **values: typing.Any):
        """
        Construct a native value from trusted field values.

            Native records retain C++ invariants. This validates input rather than
            creating an invalid object.

        """

    @classmethod
    def model_json_schema(cls, **_: typing.Any) -> dict[str, typing.Any]: ...
    @classmethod
    def model_validate(cls, value: typing.Any, **_: typing.Any): ...
    @classmethod
    def model_validate_json(
        cls, value: str | bytes | bytearray, **_: typing.Any
    ): ...
    def __copy__(self) -> ChunkMetadata: ...
    def __deepcopy__(self, memo: dict) -> ChunkMetadata: ...
    def __eq__(self, arg0: object) -> bool: ...
    def __init__(
        self,
        mimetype: str,
        timestamp: typing.Any | None = None,
        attributes: typing.Any = {},
    ) -> None: ...
    def __repr__(self) -> str: ...
    def debug_string(self) -> str: ...
    def get_attribute(self, arg0: str) -> bytes: ...
    def model_copy(
        self, *, update: dict[str, typing.Any] | None = None, deep: bool = False
    ): ...
    def model_dump(
        self, *, mode: str = "python", **_: typing.Any
    ) -> dict[str, typing.Any]: ...
    def model_dump_json(self, **kwargs: typing.Any) -> str: ...
    def set_attribute(self, arg0: str, arg1: typing.Any) -> None: ...
    def to_msgpack(self) -> bytes: ...
    def validate(self) -> None: ...
    @property
    def approx_bytes(self) -> int: ...

    @property
    def attributes(self) -> _ByteMapView: ...
    @attributes.setter
    def attributes(self, arg1: typing.Any) -> None: ...

class ChunkStore:
    def __init__(self) -> None: ...
    def clear_data(self, arg0: typing.SupportsInt) -> typing.Any: ...
    def close_writes_with_status(
        self, status: typing.Any, return_status_if_already_closed: bool = False
    ) -> typing.Any: ...
    def get(
        self, seq: typing.SupportsInt, deadline: typing.Any | None = None
    ) -> typing.Any: ...
    def get_by_arrival_order(
        self,
        arrival_order: typing.SupportsInt,
        deadline: typing.Any | None = None,
    ) -> typing.Any: ...
    def get_final_seq(self) -> typing.Any: ...
    def get_id(self) -> str: ...
    def get_seq_for_arrival_order(
        self, arg0: typing.SupportsInt
    ) -> typing.Any: ...
    def next(
        self, deadline: typing.Any | None = None, limit: typing.SupportsInt = 1
    ) -> typing.Any: ...
    def put(self, arg0: NodeFragment) -> typing.Any: ...
    def put_many(
        self, arg0: collections.abc.Sequence[NodeFragment]
    ) -> typing.Any: ...
    def size(self) -> typing.Any: ...

class ChunkStoreReader:
    def __aiter__(self) -> ChunkStoreReader: ...
    async def __anext__(self) -> NodeFragment: ...
    def __init__(
        self,
        store: ChunkStore,
        options: ChunkStoreReaderOptions | dict[str, typing.Any] | None = None,
    ) -> None: ...
    def next(self, timeout: Duration = ...): ...
    def cancel(self) -> None: ...
    def ensure_started(self) -> None: ...
    def get_status(self) -> typing.Any: ...
    def wait(self) -> typing.Any: ...
    @property
    def buffer_size(self) -> int: ...
    @property
    def options(self) -> ChunkStoreReaderOptions: ...
    @property
    def store(self) -> ChunkStore: ...

class ChunkStoreReaderOptions:
    _a11_options_installed: typing.ClassVar[bool] = True
    ordered: bool
    pop_chunks: bool
    @staticmethod
    def __get_pydantic_core_schema__(option_cls, _source_type, _handler): ...
    @staticmethod
    def __get_pydantic_json_schema__(option_cls, _schema, _handler): ...
    @staticmethod
    def model_json_schema(
        option_cls, **_: typing.Any
    ) -> dict[str, typing.Any]: ...
    @staticmethod
    def model_validate(option_cls, value: typing.Any, **_: typing.Any): ...
    def __copy__(self): ...
    def __deepcopy__(self, _memo): ...
    def __eq__(self, other: object) -> bool: ...
    def __init__(
        self,
        ordered: bool = True,
        pop_chunks: bool = False,
        num_chunks_to_buffer: typing.Any = 32,
        offset: typing.Any = 0,
        max_chunks_to_read: typing.Any | None = None,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def model_copy(
        self,
        *,
        update: collections.abc.Mapping[str, typing.Any] | None = None,
        deep: bool = False,
    ): ...
    def model_dump(self, **_: typing.Any) -> dict[str, typing.Any]: ...
    def validate(self) -> None: ...

    @property
    def max_chunks_to_read(self) -> int | None: ...
    @max_chunks_to_read.setter
    def max_chunks_to_read(self, arg0: typing.SupportsInt | None) -> None: ...

    @property
    def num_chunks_to_buffer(self) -> int: ...
    @num_chunks_to_buffer.setter
    def num_chunks_to_buffer(self, arg0: typing.SupportsInt) -> None: ...

    @property
    def offset(self) -> int: ...
    @offset.setter
    def offset(self, arg0: typing.SupportsInt) -> None: ...

class ChunkStoreWriter:
    def __init__(
        self,
        chunk_store: ChunkStore,
        options: ChunkStoreWriterOptions | dict[str, typing.Any] | None = None,
    ) -> None: ...
    async def put(
        self, obj: typing.Any, seq: int | None = None, final: bool = False
    ) -> asyncio.Future[int]: ...
    async def put_chunk(
        self, chunk: Chunk, seq: int | None = None, final: bool = False
    ) -> asyncio.Future[int]: ...
    def abort_with_status(self, arg0: typing.Any) -> typing.Any: ...
    def attach_stream(self, arg0: WireStream) -> None: ...
    def cancel(self) -> typing.Any: ...
    def detach_stream(self, arg0: WireStream) -> None: ...
    def drain_and_close(self) -> typing.Any: ...
    def enqueue_chunk(
        self, chunk: Chunk, seq: typing.Any | None = None, final: bool = False
    ) -> tuple: ...
    def ensure_started(self) -> None: ...
    def get_abort_status(self) -> typing.Any: ...
    def get_status(self) -> typing.Any: ...
    def is_writable(self) -> bool: ...
    def wait_for_buffer_to_drain(self) -> typing.Any: ...
    @property
    def options(self) -> ChunkStoreWriterOptions: ...
    @property
    def queue_size(self) -> int: ...
    @property
    def store(self) -> ChunkStore: ...

class ChunkStoreWriterOptions:
    _a11_options_installed: typing.ClassVar[bool] = True
    @staticmethod
    def __get_pydantic_core_schema__(option_cls, _source_type, _handler): ...
    @staticmethod
    def __get_pydantic_json_schema__(option_cls, _schema, _handler): ...
    @staticmethod
    def model_json_schema(
        option_cls, **_: typing.Any
    ) -> dict[str, typing.Any]: ...
    @staticmethod
    def model_validate(option_cls, value: typing.Any, **_: typing.Any): ...
    def __copy__(self): ...
    def __deepcopy__(self, _memo): ...
    def __eq__(self, other: object) -> bool: ...
    def __init__(
        self,
        offset: typing.Any = 0,
        max_chunks_to_write_at_once: typing.Any = 8,
        num_chunks_to_buffer: typing.Any | None = None,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def model_copy(
        self,
        *,
        update: collections.abc.Mapping[str, typing.Any] | None = None,
        deep: bool = False,
    ): ...
    def model_dump(self, **_: typing.Any) -> dict[str, typing.Any]: ...
    def validate(self) -> None: ...

    @property
    def max_chunks_to_write_at_once(self) -> int: ...
    @max_chunks_to_write_at_once.setter
    def max_chunks_to_write_at_once(self, arg0: typing.SupportsInt) -> None: ...

    @property
    def num_chunks_to_buffer(self) -> int | None: ...
    @num_chunks_to_buffer.setter
    def num_chunks_to_buffer(self, arg0: typing.SupportsInt | None) -> None: ...

    @property
    def offset(self) -> int: ...
    @offset.setter
    def offset(self, arg0: typing.SupportsInt) -> None: ...

class Duration:
    @staticmethod
    def _negative_infinity() -> Duration: ...
    @staticmethod
    def _positive_infinity() -> Duration: ...
    @staticmethod
    def microseconds(value: typing.SupportsFloat | None) -> Duration: ...
    @staticmethod
    def milliseconds(value: typing.SupportsFloat | None) -> Duration: ...
    @staticmethod
    def nanoseconds(value: typing.SupportsInt | None) -> Duration: ...
    @staticmethod
    def seconds(value: typing.SupportsFloat | None) -> Duration: ...
    def __add__(self, arg0: Duration) -> Duration: ...
    def __copy__(self): ...
    def __deepcopy__(self, _memo): ...
    def __eq__(self, arg0: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __init__(self, nanoseconds: typing.SupportsInt) -> None: ...
    def __le__(self, arg0: Duration) -> bool: ...
    def __lt__(self, arg0: Duration) -> bool: ...
    def __neg__(self) -> Duration: ...
    def __repr__(self) -> str: ...
    def __sub__(self, arg0: Duration) -> Duration: ...
    def float_seconds(
        self, infinity_value: typing.Any | None = None
    ) -> typing.Any: ...
    def is_infinite(self) -> bool: ...
    @property
    def nanoseconds_value(self) -> int: ...

class Http2Client:
    async def __aenter__(self) -> Http2Client: ...
    async def __aexit__(self, exc_type, exc, traceback) -> None: ...
    @staticmethod
    def connect(
        host: str, port: typing.SupportsInt, options: Http2Options = ...
    ) -> typing.Any: ...
    def close(self) -> None: ...
    def extended_connect(
        self,
        protocol: str,
        path: str,
        headers: typing.Any | None = None,
        scheme: str = "",
    ) -> Http2DuplexStream: ...
    def get_impl(self) -> typing.Any: ...
    def request(
        self,
        method: str,
        path: str,
        headers: typing.Any | None = None,
        body: typing.Any = b"",
        scheme: str = "",
    ) -> typing.Any: ...
    def request_stream(
        self,
        method: str,
        path: str,
        headers: typing.Any | None = None,
        body: typing.Any = b"",
        scheme: str = "",
    ) -> Http2ResponseStream: ...
    @property
    def connected(self) -> bool: ...
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def secure(self) -> bool: ...

class Http2DuplexStream:
    def __aiter__(self): ...
    async def __anext__(self) -> bytes: ...
    def abort(self, status: typing.Any | None = None) -> None: ...
    def finish(self) -> None: ...
    def headers(self) -> typing.Any: ...
    def read(self) -> typing.Any: ...
    def wait_done(self) -> typing.Any: ...
    def write(self, arg0: typing.Any) -> None: ...
    @property
    def done(self) -> typing.Any: ...
    @property
    def stream_id(self) -> int: ...

class Http2Options:
    deadline: typing.Any
    tls: Http2TlsOptions
    def __init__(self) -> None: ...
    def validate(self) -> None: ...

    @property
    def max_buffered_request_bytes(self) -> int: ...
    @max_buffered_request_bytes.setter
    def max_buffered_request_bytes(self, arg0: typing.SupportsInt) -> None: ...

    @property
    def max_buffered_response_bytes(self) -> int: ...
    @max_buffered_response_bytes.setter
    def max_buffered_response_bytes(self, arg0: typing.SupportsInt) -> None: ...

    @property
    def max_request_body_size(self) -> int: ...
    @max_request_body_size.setter
    def max_request_body_size(self, arg0: typing.SupportsInt) -> None: ...

    @property
    def max_response_body_size(self) -> int: ...
    @max_response_body_size.setter
    def max_response_body_size(self, arg0: typing.SupportsInt) -> None: ...

class Http2RequestBodyStream:
    def __aiter__(self): ...
    async def __anext__(self) -> bytes: ...
    def cancel(self, status: typing.Any | None = None) -> None: ...
    def read(self) -> typing.Any: ...
    def wait_done(self) -> typing.Any: ...
    @property
    def done(self) -> typing.Any: ...
    @property
    def stream_id(self) -> int: ...

class Http2ResponseStream:
    def __aiter__(self): ...
    async def __anext__(self) -> bytes: ...
    def cancel(self, status: typing.Any | None = None) -> None: ...
    def headers(self) -> typing.Any: ...
    def read(self) -> typing.Any: ...
    def wait_done(self) -> typing.Any: ...
    @property
    def done(self) -> typing.Any: ...
    @property
    def stream_id(self) -> int: ...

class Http2ResponseWriter:
    def abort(self, arg0: typing.Any) -> None: ...
    def finish(self) -> None: ...
    def send_headers(
        self, status: typing.SupportsInt, headers: typing.Any | None = None
    ) -> None: ...
    def send_response(
        self,
        status: typing.SupportsInt,
        headers: typing.Any | None = None,
        body: typing.Any = b"",
    ) -> None: ...
    def wait_done(self) -> typing.Any: ...
    def write(self, arg0: typing.Any) -> None: ...
    @property
    def done(self) -> typing.Any: ...
    @property
    def finished(self) -> bool: ...
    @property
    def headers_sent(self) -> bool: ...
    @property
    def stream_id(self) -> int: ...

class Http2Server:
    def __enter__(self) -> Http2Server: ...
    def __exit__(self, exc_type, exc, traceback) -> None: ...
    @staticmethod
    def create(
        bind_address: str = "127.0.0.1",
        port: typing.SupportsInt = 0,
        handler: typing.Any | None = None,
        options: Http2Options = ...,
    ) -> Http2Server: ...
    def get_impl(self) -> typing.Any: ...
    def stop(self) -> None: ...
    @property
    def bind_address(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def running(self) -> bool: ...
    @property
    def secure(self) -> bool: ...

class Http2TlsOptions:
    ca_certificate_pem_file: str
    certificate_pem_file: str
    enabled: bool
    key_pem_file: str
    verify_peer: bool
    def __init__(self) -> None: ...
    def validate(self) -> None: ...

class HttpRequest:
    authority: str
    method: str
    path: str
    protocol: str
    scheme: str
    def __init__(
        self,
        method: str = "GET",
        scheme: str = "http",
        authority: str = "",
        path: str = "/",
        headers: typing.Any | None = None,
        body: typing.Any = b"",
    ) -> None: ...

    @property
    def body(self) -> bytes: ...
    @body.setter
    def body(self, arg1: typing.Any) -> None: ...

    @property
    def body_stream(self) -> Http2RequestBodyStream: ...

    @property
    def headers(self) -> list: ...
    @headers.setter
    def headers(self, arg1: typing.Any) -> None: ...

class HttpResponse:
    head: HttpResponseHead
    def __init__(
        self, head: HttpResponseHead = ..., body: typing.Any = b""
    ) -> None: ...

    @property
    def body(self) -> bytes: ...
    @body.setter
    def body(self, arg1: typing.Any) -> None: ...

class HttpResponseHead:
    def __init__(
        self, status: typing.SupportsInt = 0, headers: typing.Any | None = None
    ) -> None: ...

    @property
    def headers(self) -> list: ...
    @headers.setter
    def headers(self, arg1: typing.Any) -> None: ...

    @property
    def status(self) -> int: ...
    @status.setter
    def status(self, arg0: typing.SupportsInt) -> None: ...

class HttpSseClientWireStream(HttpSseWireStream):
    @staticmethod
    def create(
        url: str,
        options: HttpSseOptions = ...,
        client: Http2Client | None = None,
        request_headers: typing.Any | None = None,
    ) -> HttpSseClientWireStream: ...
    def __init__(
        self,
        url: str,
        options: HttpSseOptions = ...,
        client: Http2Client | None = None,
        request_headers: typing.Any | None = None,
    ) -> None: ...
    @property
    def client(self) -> Http2Client: ...

class HttpSseOptions:
    connect_endpoint: str
    http2_options: Http2Options
    message_endpoint: str
    stream_options: WireStreamOptions
    def __init__(self) -> None: ...
    def validate(self) -> None: ...

class HttpSseServer:
    def __enter__(self) -> HttpSseServer: ...
    def __exit__(self, exc_type, exc, traceback) -> None: ...
    @staticmethod
    def create(
        bind_address: str = "127.0.0.1",
        port: typing.SupportsInt = 0,
        on_connect: typing.Any | None = None,
        options: HttpSseOptions = ...,
    ) -> HttpSseServer: ...
    def stop(self) -> None: ...
    def wait_for_stream(self) -> typing.Any: ...
    @property
    def http2_server(self) -> Http2Server: ...
    @property
    def port(self) -> int: ...
    @property
    def running(self) -> bool: ...

class HttpSseServerWireStream(HttpSseWireStream):
    def accepted(self) -> typing.Any: ...

class HttpSseWireStream(WireStream):
    def get_http_request_headers(self) -> list: ...
    def get_http_response_headers(self) -> typing.Any: ...
    def set_http_request_headers(self, arg0: typing.Any) -> None: ...
    def set_http_response_headers(self, arg0: typing.Any) -> None: ...
    def wait_for_http_headers(self) -> typing.Any: ...

class InProcessWireStream(WireStream):
    @staticmethod
    def create_pair(
        options: WireStreamOptions | None = None,
        first_options: WireStreamOptions | None = None,
        second_options: WireStreamOptions | None = None,
    ) -> tuple[InProcessWireStream, InProcessWireStream]: ...
    def wait(self) -> typing.Any: ...

class LocalChunkStore(ChunkStore):
    @staticmethod
    def create(node_id: str) -> LocalChunkStore: ...
    def __init__(self, arg0: str) -> None: ...

class NodeFragment:
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    continued: bool
    data: typing.Any
    id: str
    @staticmethod
    def from_msgpack(data: typing.Any) -> NodeFragment: ...
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler): ...
    @classmethod
    def __get_pydantic_json_schema__(cls, _schema, _handler): ...
    @classmethod
    def model_construct(cls, **values: typing.Any):
        """
        Construct a native value from trusted field values.

            Native records retain C++ invariants. This validates input rather than
            creating an invalid object.

        """

    @classmethod
    def model_json_schema(cls, **_: typing.Any) -> dict[str, typing.Any]: ...
    @classmethod
    def model_validate(cls, value: typing.Any, **_: typing.Any): ...
    @classmethod
    def model_validate_json(
        cls, value: str | bytes | bytearray, **_: typing.Any
    ): ...
    def __copy__(self) -> NodeFragment: ...
    def __deepcopy__(self, memo: dict) -> NodeFragment: ...
    def __eq__(self, arg0: object) -> bool: ...
    def __init__(
        self,
        data: typing.Any,
        id: str = "",
        seq: typing.Any | None = None,
        continued: bool = False,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def debug_string(self) -> str: ...
    def get_chunk(self) -> Chunk: ...
    def get_node_ref(self) -> NodeRef: ...
    def model_copy(
        self, *, update: dict[str, typing.Any] | None = None, deep: bool = False
    ): ...
    def model_dump(
        self, *, mode: str = "python", **_: typing.Any
    ) -> dict[str, typing.Any]: ...
    def model_dump_json(self, **kwargs: typing.Any) -> str: ...
    def to_msgpack(self) -> bytes: ...
    def validate(self) -> None: ...
    @property
    def approx_bytes(self) -> int: ...

    @property
    def seq(self) -> int | None: ...
    @seq.setter
    def seq(self, arg0: typing.SupportsInt | None) -> None: ...

class NodeMap:
    @staticmethod
    def __getitem__(*args, **kwargs):
        """
        get(self: NodeMap, arg0: str) -> a11::nodes::AsyncNode
        """

    def __contains__(self, arg0: str) -> bool: ...
    def __init__(
        self, chunk_store_factory: typing.Any | None = None
    ) -> None: ...
    def __len__(self) -> int: ...
    def contains(self, arg0: str) -> bool: ...
    def discard(
        self, node_id: str, expected: AsyncNode | None = None
    ) -> AsyncNode | None: ...
    def get(self, arg0: str) -> AsyncNode: ...
    def get_if_exists(self, arg0: str) -> AsyncNode | None: ...
    def size(self) -> int: ...

class NodeRef:
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    id: str
    @staticmethod
    def from_msgpack(data: typing.Any) -> NodeRef: ...
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler): ...
    @classmethod
    def __get_pydantic_json_schema__(cls, _schema, _handler): ...
    @classmethod
    def model_construct(cls, **values: typing.Any):
        """
        Construct a native value from trusted field values.

            Native records retain C++ invariants. This validates input rather than
            creating an invalid object.

        """

    @classmethod
    def model_json_schema(cls, **_: typing.Any) -> dict[str, typing.Any]: ...
    @classmethod
    def model_validate(cls, value: typing.Any, **_: typing.Any): ...
    @classmethod
    def model_validate_json(
        cls, value: str | bytes | bytearray, **_: typing.Any
    ): ...
    def __copy__(self) -> NodeRef: ...
    def __deepcopy__(self, memo: dict) -> NodeRef: ...
    def __eq__(self, arg0: object) -> bool: ...
    def __init__(
        self, id: str, offset: typing.Any = 0, length: typing.Any | None = None
    ) -> None: ...
    def __repr__(self) -> str: ...
    def debug_string(self) -> str: ...
    def model_copy(
        self, *, update: dict[str, typing.Any] | None = None, deep: bool = False
    ): ...
    def model_dump(
        self, *, mode: str = "python", **_: typing.Any
    ) -> dict[str, typing.Any]: ...
    def model_dump_json(self, **kwargs: typing.Any) -> str: ...
    def to_msgpack(self) -> bytes: ...
    def validate(self) -> None: ...
    @property
    def approx_bytes(self) -> int: ...

    @property
    def length(self) -> int | None: ...
    @length.setter
    def length(self, arg0: typing.SupportsInt | None) -> None: ...

    @property
    def offset(self) -> int: ...
    @offset.setter
    def offset(self, arg0: typing.SupportsInt) -> None: ...

class Port:
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    id: str
    name: str
    @staticmethod
    def from_msgpack(data: typing.Any) -> Port: ...
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler): ...
    @classmethod
    def __get_pydantic_json_schema__(cls, _schema, _handler): ...
    @classmethod
    def model_construct(cls, **values: typing.Any):
        """
        Construct a native value from trusted field values.

            Native records retain C++ invariants. This validates input rather than
            creating an invalid object.

        """

    @classmethod
    def model_json_schema(cls, **_: typing.Any) -> dict[str, typing.Any]: ...
    @classmethod
    def model_validate(cls, value: typing.Any, **_: typing.Any): ...
    @classmethod
    def model_validate_json(
        cls, value: str | bytes | bytearray, **_: typing.Any
    ): ...
    def __copy__(self) -> Port: ...
    def __deepcopy__(self, memo: dict) -> Port: ...
    def __eq__(self, arg0: object) -> bool: ...
    def __init__(self, name: str = "", id: str = "") -> None: ...
    def __repr__(self) -> str: ...
    def debug_string(self) -> str: ...
    def model_copy(
        self, *, update: dict[str, typing.Any] | None = None, deep: bool = False
    ): ...
    def model_dump(
        self, *, mode: str = "python", **_: typing.Any
    ) -> dict[str, typing.Any]: ...
    def model_dump_json(self, **kwargs: typing.Any) -> str: ...
    def to_msgpack(self) -> bytes: ...
    def validate(self) -> None: ...
    @property
    def approx_bytes(self) -> int: ...

class SerializationRegistry:
    def __init__(self, register_defaults: bool = False) -> None: ...
    def register_defaults(self) -> None: ...
    @property
    def deserializer_count(self) -> int: ...
    @property
    def serializer_count(self) -> int: ...

class Session:
    action_registry: ActionRegistry | None
    node_map: NodeMap
    def __init__(
        self,
        session_id: str = "",
        on_stream_message: typing.Any | None = None,
        on_stream_done: typing.Any | None = None,
        headers: typing.Any | None = None,
        options: SessionOptions | None = None,
        node_map: NodeMap | None = None,
        action_registry: ActionRegistry | None = None,
    ) -> None: ...
    def abort(self, arg0: typing.Any) -> None: ...
    def actions(self) -> list[tuple[str, Action]]: ...
    def add_stream(
        self, stream: WireStream, mode: typing.Any = "start"
    ) -> typing.Any: ...
    def await_all_actions(
        self, timeout: typing.Any | None = None
    ) -> typing.Any: ...
    def cancel_action(self, arg0: str) -> None: ...
    def cancel_all_actions(self) -> None: ...
    def dispatch_action(self, arg0: typing.Any) -> typing.Any: ...
    def dispatch_action_message(
        self,
        action_message: ActionMessage,
        origin_stream: WireStream | None = None,
    ) -> typing.Any: ...
    def dispatch_node_fragment(self, arg0: NodeFragment) -> typing.Any: ...
    def dispatch_wire_message(
        self, message: WireMessage, origin_stream: WireStream | None = None
    ) -> typing.Any: ...
    def get_action(self, arg0: str) -> Action: ...
    def get_action_registry(self) -> ActionRegistry | None: ...
    def get_id(self) -> str: ...
    def get_node_map(self) -> NodeMap: ...
    def get_status(self) -> typing.Any: ...
    def get_stream(self, arg0: str) -> WireStream: ...
    def half_close(self) -> None: ...
    def is_closed(self) -> bool: ...
    def is_done(self) -> bool: ...
    def send(self, message: WireMessage, stream_id: str = "") -> None: ...
    def set_action_registry(self, arg0: ActionRegistry) -> None: ...
    def set_deadline(self, deadline: typing.Any | None = None) -> None: ...
    def set_node_map(self, arg0: NodeMap) -> None: ...
    def streams(self) -> list[tuple[str, WireStream]]: ...
    def wait_done(self) -> typing.Any: ...
    @property
    def deadline(self) -> typing.Any: ...
    @property
    def done(self) -> _DoneEvent: ...
    @property
    def id(self) -> str: ...

class SessionOptions:
    _a11_options_installed: typing.ClassVar[bool] = True
    deadline: typing.Any
    no_stream_timeout: typing.Any
    @staticmethod
    def __get_pydantic_core_schema__(option_cls, _source_type, _handler): ...
    @staticmethod
    def __get_pydantic_json_schema__(option_cls, _schema, _handler): ...
    @staticmethod
    def model_json_schema(
        option_cls, **_: typing.Any
    ) -> dict[str, typing.Any]: ...
    @staticmethod
    def model_validate(option_cls, value: typing.Any, **_: typing.Any): ...
    def __copy__(self): ...
    def __deepcopy__(self, _memo): ...
    def __eq__(self, other: object) -> bool: ...
    def __init__(
        self,
        *,
        max_buffered_messages_total: typing.Any = 256,
        max_buffered_messages_per_stream: typing.Any = 32,
        max_concurrent_root_actions: typing.Any = 32,
        max_concurrent_nested_actions: typing.Any = 128,
        max_single_message_size: typing.Any = 33554432,
        max_buffered_bytes_total: typing.Any = 33554432,
        max_buffered_bytes_per_stream: typing.Any = 4194304,
        no_stream_timeout: typing.Any | None = None,
        deadline: typing.Any | None = None,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def model_copy(
        self,
        *,
        update: collections.abc.Mapping[str, typing.Any] | None = None,
        deep: bool = False,
    ): ...
    def model_dump(self, **_: typing.Any) -> dict[str, typing.Any]: ...
    def validate(self) -> None: ...

    @property
    def max_buffered_bytes_per_stream(self) -> int: ...
    @max_buffered_bytes_per_stream.setter
    def max_buffered_bytes_per_stream(
        self, arg0: typing.SupportsInt
    ) -> None: ...

    @property
    def max_buffered_bytes_total(self) -> int: ...
    @max_buffered_bytes_total.setter
    def max_buffered_bytes_total(self, arg0: typing.SupportsInt) -> None: ...

    @property
    def max_buffered_messages_per_stream(self) -> int: ...
    @max_buffered_messages_per_stream.setter
    def max_buffered_messages_per_stream(
        self, arg0: typing.SupportsInt
    ) -> None: ...

    @property
    def max_buffered_messages_total(self) -> int: ...
    @max_buffered_messages_total.setter
    def max_buffered_messages_total(self, arg0: typing.SupportsInt) -> None: ...

    @property
    def max_concurrent_nested_actions(self) -> int: ...
    @max_concurrent_nested_actions.setter
    def max_concurrent_nested_actions(
        self, arg0: typing.SupportsInt
    ) -> None: ...

    @property
    def max_concurrent_root_actions(self) -> int: ...
    @max_concurrent_root_actions.setter
    def max_concurrent_root_actions(self, arg0: typing.SupportsInt) -> None: ...

    @property
    def max_single_message_size(self) -> int: ...
    @max_single_message_size.setter
    def max_single_message_size(self, arg0: typing.SupportsInt) -> None: ...

class SessionWithRecv(Session):
    async def receive(self, deadline=None): ...
    async def receive_with_stream_id(self, deadline=None): ...
    def __init__(
        self,
        session_id: str = "",
        headers: typing.Any | None = None,
        options: SessionOptions | None = None,
        node_map: NodeMap | None = None,
        action_registry: ActionRegistry | None = None,
    ) -> None: ...

class SignallingEndpoint(SignallingTransport):
    pass

class SignallingMessage:
    candidate: str
    description: str
    description_type: str
    error: typing.Any
    mid: str
    recipient: str
    sender: str
    type: SignallingMessageType
    @staticmethod
    def from_json(arg0: str) -> SignallingMessage: ...
    def __init__(
        self,
        type: SignallingMessageType = ...,
        sender: str = "",
        recipient: str = "",
        description: str = "",
        description_type: str = "",
        candidate: str = "",
        mid: str = "",
        error: typing.Any | None = None,
    ) -> None: ...
    def to_json(self) -> str: ...
    def validate(self) -> None: ...

class SignallingMessageType:
    """
    Members:

      DESCRIPTION

      CANDIDATE

      ERROR
    """

    CANDIDATE: typing.ClassVar[SignallingMessageType]
    DESCRIPTION: typing.ClassVar[SignallingMessageType]
    ERROR: typing.ClassVar[SignallingMessageType]
    __members__: typing.ClassVar[dict[str, SignallingMessageType]]
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: typing.SupportsInt) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class SignallingService:
    def __enter__(self) -> SignallingService: ...
    def __exit__(self, exc_type, exc, traceback) -> None: ...
    @staticmethod
    def create() -> SignallingService: ...
    def __contains__(self, arg0: str) -> bool: ...
    def __init__(self) -> None: ...
    def connect(self, arg0: str, arg1: typing.Any) -> SignallingEndpoint: ...
    def contains(self, arg0: str) -> bool: ...
    def identities(self) -> list[str]: ...
    def stop(self) -> None: ...

class SignallingTransport:
    def __enter__(self) -> SignallingTransport: ...
    def __exit__(self, exc_type, exc, traceback) -> None: ...
    def __init__(self) -> None: ...
    def close(self) -> None: ...
    def connected(self) -> bool: ...
    def get_status(self) -> typing.Any: ...
    def identity(self) -> str: ...
    def send(self, arg0: SignallingMessage) -> None: ...
    def set_on_message(self, arg0: typing.Any) -> None: ...

class Status:
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    details: typing.Any
    message: str
    @staticmethod
    def from_exception(
        exc: BaseException,
        casters: a11.status.StatusExceptionCasters | None = None,
    ) -> Status: ...
    @staticmethod
    def from_http_exception(
        http_exception: (
            fastapi.exceptions.HTTPException | httpx.HTTPStatusError
        ),
    ) -> Status: ...
    @staticmethod
    def get_fastapi_response_dict_for_codes(
        *codes: a11.status.StatusCode,
    ) -> dict[int, dict]: ...
    @staticmethod
    def get_fastapi_response_dict_for_http_codes(
        *codes: int,
    ) -> dict[int, dict]: ...
    @staticmethod
    def ok(message: str | None = None) -> Status: ...
    @staticmethod
    def parse_from_json(data: str | bytes) -> a11.status.StatusParseResult: ...
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler): ...
    @classmethod
    def __get_pydantic_json_schema__(cls, _schema, _handler): ...
    @classmethod
    def model_json_schema(
        cls, **kwargs: typing.Any
    ) -> dict[str, typing.Any]: ...
    @classmethod
    def model_validate(cls, value: typing.Any, **_: typing.Any) -> Status: ...
    def __copy__(self): ...
    def __deepcopy__(self, _memo): ...
    def __eq__(self, arg0: object) -> bool: ...
    def __init__(
        self,
        code: typing.SupportsInt = 0,
        message: str = "OK",
        details: typing.Any = [],
    ) -> None: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> typing.Any: ...
    def _as_dict(self) -> typing.Any: ...
    def _copy(self) -> Status: ...
    def is_ok(self) -> bool: ...
    def model_copy(
        self, *, update: dict[str, typing.Any] | None = None, deep: bool = False
    ) -> Status: ...
    def model_dump(
        self, *, mode: str = "python", **_: typing.Any
    ) -> dict[str, typing.Any]: ...
    def model_dump_json(self, **kwargs: typing.Any) -> str: ...
    def raise_if_not_ok(self) -> None: ...
    def to_exception(self) -> a11.status.StatusException: ...
    def to_msgpack(self, packer: msgpack._cmsgpack.Packer) -> None: ...

    @property
    def code(self) -> typing.Any: ...
    @code.setter
    def code(self, arg1: typing.SupportsInt) -> None: ...

class StreamMode:
    """
    Members:

      START

      ACCEPT
    """

    ACCEPT: typing.ClassVar[StreamMode]
    START: typing.ClassVar[StreamMode]
    __members__: typing.ClassVar[dict[str, StreamMode]]
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: typing.SupportsInt) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class Time:
    @staticmethod
    def _infinite_future() -> Time: ...
    @staticmethod
    def _infinite_past() -> Time: ...
    @staticmethod
    def _now() -> Time: ...
    @staticmethod
    def from_nanoseconds_since_epoch(arg0: typing.SupportsInt) -> Time: ...
    def __add__(self, arg0: Duration) -> Time: ...
    def __copy__(self): ...
    def __deepcopy__(self, _memo): ...
    def __eq__(self, arg0: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __init__(self, nanoseconds_since_epoch: typing.SupportsInt) -> None: ...
    def __le__(self, arg0: Time) -> bool: ...
    def __lt__(self, arg0: Time) -> bool: ...
    def __repr__(self) -> str: ...
    def __sub__(self, arg0: typing.Any) -> typing.Any: ...
    @property
    def nanoseconds_since_epoch(self) -> int: ...

class TurnRelayType:
    """
    Members:

      UDP

      TCP

      TLS
    """

    TCP: typing.ClassVar[TurnRelayType]
    TLS: typing.ClassVar[TurnRelayType]
    UDP: typing.ClassVar[TurnRelayType]
    __members__: typing.ClassVar[dict[str, TurnRelayType]]
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: typing.SupportsInt) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: typing.SupportsInt) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class TurnServer:
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    hostname: str
    password: str
    relay_type: TurnRelayType
    username: str
    @staticmethod
    def from_string(arg0: str) -> TurnServer: ...
    def __eq__(self, arg0: object) -> bool: ...
    def __init__(self) -> None: ...

    @property
    def port(self) -> int: ...
    @port.setter
    def port(self, arg0: typing.SupportsInt) -> None: ...

class WebRtcConfiguration:
    bind_address: str | None
    enable_ice_udp_mux: bool
    def __init__(self) -> None: ...
    def validate(self) -> None: ...

    @property
    def channel_split_size(self) -> int: ...
    @channel_split_size.setter
    def channel_split_size(self, arg0: typing.SupportsInt) -> None: ...

    @property
    def max_message_size(self) -> int | None: ...
    @max_message_size.setter
    def max_message_size(self, arg0: typing.SupportsInt | None) -> None: ...

    @property
    def preferred_port_range(self) -> tuple[int, int] | None: ...
    @preferred_port_range.setter
    def preferred_port_range(
        self, arg0: tuple[typing.SupportsInt, typing.SupportsInt] | None
    ) -> None: ...

    @property
    def stun_servers(self) -> list[str]: ...
    @stun_servers.setter
    def stun_servers(self, arg0: collections.abc.Sequence[str]) -> None: ...

    @property
    def turn_servers(self) -> list[TurnServer]: ...
    @turn_servers.setter
    def turn_servers(
        self, arg0: collections.abc.Sequence[TurnServer]
    ) -> None: ...

class WebRtcWireServer:
    def __enter__(self) -> WebRtcWireServer: ...
    def __exit__(self, exc_type, exc, traceback) -> None: ...
    @staticmethod
    def create(
        identity: str,
        signalling: SignallingService,
        on_stream: typing.Any,
        configuration: WebRtcConfiguration = ...,
        stream_options: WireStreamOptions = ...,
    ) -> WebRtcWireServer: ...
    def stop(self) -> None: ...
    @property
    def identity(self) -> str: ...
    @property
    def pending_peer_count(self) -> int: ...
    @property
    def running(self) -> bool: ...
    @property
    def signalling_endpoint(self) -> SignallingEndpoint: ...

class WebRtcWireStream(WireStream):
    @staticmethod
    @typing.overload
    def create_client(
        identity: str,
        peer_identity: str,
        signalling: SignallingService,
        configuration: WebRtcConfiguration = ...,
        options: WireStreamOptions = ...,
    ) -> WebRtcWireStream: ...
    @staticmethod
    @typing.overload
    def create_client(
        peer_identity: str,
        signalling: SignallingTransport,
        configuration: WebRtcConfiguration = ...,
        options: WireStreamOptions = ...,
    ) -> WebRtcWireStream: ...

    @property
    def data_channel(self) -> typing.Any: ...
    @property
    def peer_connection(self) -> typing.Any: ...
    @property
    def signalling_endpoint(self) -> SignallingTransport: ...

class WebSocketClientOptions:
    framing: ChannelFramingOptions
    http2_options: Http2Options
    def __init__(self) -> None: ...
    def validate(self) -> None: ...

    @property
    def headers(self) -> list: ...
    @headers.setter
    def headers(self, arg1: typing.Any) -> None: ...

class WebSocketServerOptions:
    bind_address: str
    enable_tls: bool
    framing: ChannelFramingOptions
    http2_options: Http2Options
    path: str
    stream_options: WireStreamOptions
    def __init__(self) -> None: ...
    def validate(self) -> None: ...

    @property
    def port(self) -> int: ...
    @port.setter
    def port(self, arg0: typing.SupportsInt) -> None: ...

class WebSocketSignallingClient(SignallingTransport):
    @staticmethod
    def connect(
        url: str,
        identity: str,
        on_message: typing.Any | None = None,
        options: WebSocketSignallingClientOptions = ...,
    ) -> typing.Any: ...
    def get_impl(self) -> typing.Any: ...

class WebSocketSignallingClientOptions:
    deadline: typing.Any
    http2_options: Http2Options
    def __init__(self) -> None: ...
    def validate(self) -> None: ...

    @property
    def max_message_size(self) -> int: ...
    @max_message_size.setter
    def max_message_size(self, arg0: typing.SupportsInt) -> None: ...

class WebSocketSignallingServer:
    def __enter__(self) -> WebSocketSignallingServer: ...
    def __exit__(self, exc_type, exc, traceback) -> None: ...
    @staticmethod
    def create(
        service: SignallingService,
        options: WebSocketSignallingServerOptions = ...,
    ) -> WebSocketSignallingServer: ...
    def get_impl(self) -> typing.Any: ...
    def stop(self) -> None: ...
    @property
    def port(self) -> int: ...
    @property
    def running(self) -> bool: ...
    @property
    def service(self) -> SignallingService: ...

class WebSocketSignallingServerOptions:
    bind_address: str
    enable_tls: bool
    http2_options: Http2Options
    path_prefix: str
    def __init__(self) -> None: ...
    def validate(self) -> None: ...

    @property
    def max_message_size(self) -> int: ...
    @max_message_size.setter
    def max_message_size(self, arg0: typing.SupportsInt) -> None: ...

    @property
    def port(self) -> int: ...
    @port.setter
    def port(self, arg0: typing.SupportsInt) -> None: ...

class WebSocketWireServer:
    def __enter__(self) -> WebSocketWireServer: ...
    def __exit__(self, exc_type, exc, traceback) -> None: ...
    @staticmethod
    def create(
        on_stream: typing.Any, options: WebSocketServerOptions = ...
    ) -> WebSocketWireServer: ...
    def get_impl(self) -> typing.Any: ...
    def stop(self) -> None: ...
    @property
    def port(self) -> int: ...
    @property
    def running(self) -> bool: ...

class WebSocketWireStream(WireStream):
    @staticmethod
    def connect(
        url: str,
        options: WireStreamOptions = ...,
        websocket_options: WebSocketClientOptions = ...,
    ) -> WebSocketWireStream: ...

class WireMessage:
    VERSION: typing.ClassVar[int] = 1
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    @staticmethod
    def from_json(arg0: str) -> WireMessage: ...
    @staticmethod
    def from_msgpack(data: typing.Any) -> WireMessage: ...
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler): ...
    @classmethod
    def __get_pydantic_json_schema__(cls, _schema, _handler): ...
    @classmethod
    def model_construct(cls, **values: typing.Any):
        """
        Construct a native value from trusted field values.

            Native records retain C++ invariants. This validates input rather than
            creating an invalid object.

        """

    @classmethod
    def model_json_schema(cls, **_: typing.Any) -> dict[str, typing.Any]: ...
    @classmethod
    def model_validate(cls, value: typing.Any, **_: typing.Any): ...
    @classmethod
    def model_validate_json(
        cls, value: str | bytes | bytearray, **_: typing.Any
    ): ...
    def __copy__(self) -> WireMessage: ...
    def __deepcopy__(self, memo: dict) -> WireMessage: ...
    def __eq__(self, arg0: object) -> bool: ...
    def __init__(
        self,
        node_fragments: typing.Any = [],
        actions: typing.Any = [],
        headers: typing.Any = {},
    ) -> None: ...
    def __repr__(self) -> str: ...
    def debug_string(self) -> str: ...
    def model_copy(
        self, *, update: dict[str, typing.Any] | None = None, deep: bool = False
    ): ...
    def model_dump(
        self, *, mode: str = "python", **_: typing.Any
    ) -> dict[str, typing.Any]: ...
    def model_dump_json(self, **kwargs: typing.Any) -> str: ...
    def to_json(self) -> str: ...
    def to_msgpack(self) -> bytes: ...
    def validate(self) -> None: ...

    @property
    def actions(self) -> _ActionMessageVectorView: ...
    @actions.setter
    def actions(self, arg1: typing.Any) -> None: ...

    @property
    def approx_bytes(self) -> int: ...

    @property
    def headers(self) -> _ByteMapView: ...
    @headers.setter
    def headers(self, arg1: typing.Any) -> None: ...

    @property
    def node_fragments(self) -> _NodeFragmentVectorView: ...
    @node_fragments.setter
    def node_fragments(self, arg1: typing.Any) -> None: ...

class WireStream:
    async def __aenter__(self) -> typing.Self: ...
    async def __aexit__(self, exc_type, exc, traceback) -> None: ...
    def __init__(self) -> None: ...
    def abort(self, arg0: typing.Any) -> None: ...
    def accept(self, arg0: typing.Any, arg1: typing.Any) -> typing.Any: ...
    def drain_outgoing_messages(self) -> typing.Any: ...
    def get_id(self) -> str: ...
    def get_impl(self) -> typing.Any: ...
    def get_status(self) -> typing.Any: ...
    def get_trailers(self) -> typing.Any: ...
    def half_close(self, trailers: typing.Any | None = None) -> None: ...
    def send(self, arg0: WireMessage) -> None: ...
    def set_deadline(self, deadline: typing.Any | None = None) -> None: ...
    def start(self, arg0: typing.Any, arg1: typing.Any) -> typing.Any: ...
    @property
    def deadline(self) -> typing.Any: ...

class WireStreamOptions:
    _a11_options_installed: typing.ClassVar[bool] = True
    deadline: typing.Any
    message_timeout: typing.Any
    message_timeout_millis: typing.Any
    @staticmethod
    def __get_pydantic_core_schema__(option_cls, _source_type, _handler): ...
    @staticmethod
    def __get_pydantic_json_schema__(option_cls, _schema, _handler): ...
    @staticmethod
    def model_json_schema(
        option_cls, **_: typing.Any
    ) -> dict[str, typing.Any]: ...
    @staticmethod
    def model_validate(option_cls, value: typing.Any, **_: typing.Any): ...
    def __copy__(self): ...
    def __deepcopy__(self, _memo): ...
    def __eq__(self, other: object) -> bool: ...
    def __init__(
        self,
        max_buffered_incoming_messages: typing.Any = 100,
        max_single_message_size: typing.Any = 33554432,
        max_buffered_incoming_bytes: typing.Any = 33554432,
        message_timeout_millis: typing.Any | None = None,
        deadline: typing.Any | None = None,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def model_copy(
        self,
        *,
        update: collections.abc.Mapping[str, typing.Any] | None = None,
        deep: bool = False,
    ): ...
    def model_dump(self, **_: typing.Any) -> dict[str, typing.Any]: ...
    def validate(self) -> None: ...

    @property
    def max_buffered_incoming_bytes(self) -> int: ...
    @max_buffered_incoming_bytes.setter
    def max_buffered_incoming_bytes(self, arg0: typing.SupportsInt) -> None: ...

    @property
    def max_buffered_incoming_messages(self) -> int: ...
    @max_buffered_incoming_messages.setter
    def max_buffered_incoming_messages(
        self, arg0: typing.SupportsInt
    ) -> None: ...

    @property
    def max_single_message_size(self) -> int: ...
    @max_single_message_size.setter
    def max_single_message_size(self, arg0: typing.SupportsInt) -> None: ...

class WireStreamWithRecv(WireStream):
    def __init__(self, stream: typing.Any) -> None: ...
    def accept(self) -> typing.Any: ...  # type: ignore[override]
    def receive(self, timeout: typing.Any | None = None) -> typing.Any: ...
    def start(self) -> typing.Any: ...  # type: ignore[override]
    @property
    def wrapped_stream(self) -> WireStream: ...

class _ActionHeaderSchemaMapView:
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    def __bool__(self) -> bool: ...
    def __contains__(self, arg0: str) -> bool: ...
    def __delitem__(self, arg0: str) -> None: ...
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: str) -> ActionHeaderSchema: ...
    def __iter__(self) -> typing.Any: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: str, arg1: typing.Any) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> dict: ...
    def get(
        self, key: str, default: typing.Any | None = None
    ) -> typing.Any: ...
    def items(self) -> typing.Any: ...
    def keys(self) -> typing.Any: ...
    def update(self, arg0: typing.Any) -> None: ...
    def values(self) -> typing.Any: ...

class _ActionMessageVectorView:
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    def __bool__(self) -> bool: ...
    def __contains__(self, arg0: ActionMessage) -> bool: ...

    @typing.overload
    def __delitem__(self, arg0: typing.SupportsInt) -> None: ...
    @typing.overload
    def __delitem__(self, arg0: slice) -> None: ...

    def __eq__(self, arg0: object) -> bool: ...

    @typing.overload
    def __getitem__(self, arg0: typing.SupportsInt) -> ActionMessage: ...
    @typing.overload
    def __getitem__(self, arg0: slice) -> list: ...

    def __iter__(self) -> collections.abc.Iterator[ActionMessage]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

    @typing.overload
    def __setitem__(
        self, arg0: typing.SupportsInt, arg1: ActionMessage
    ) -> None: ...
    @typing.overload
    def __setitem__(self, arg0: slice, arg1: typing.Any) -> None: ...

    def append(self, arg0: ActionMessage) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> list: ...
    def count(self, arg0: ActionMessage) -> int: ...
    def extend(self, arg0: typing.Any) -> None: ...
    def index(self, arg0: ActionMessage) -> int: ...
    def insert(self, arg0: typing.SupportsInt, arg1: ActionMessage) -> None: ...
    def pop(self, index: typing.SupportsInt = -1) -> ActionMessage: ...
    def remove(self, arg0: ActionMessage) -> None: ...
    def reverse(self) -> None: ...

class _ActionPortSchemaMapView:
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    def __bool__(self) -> bool: ...
    def __contains__(self, arg0: str) -> bool: ...
    def __delitem__(self, arg0: str) -> None: ...
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: str) -> ActionPortSchema: ...
    def __iter__(self) -> typing.Any: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: str, arg1: typing.Any) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> dict: ...
    def get(
        self, key: str, default: typing.Any | None = None
    ) -> typing.Any: ...
    def items(self) -> typing.Any: ...
    def keys(self) -> typing.Any: ...
    def update(self, arg0: typing.Any) -> None: ...
    def values(self) -> typing.Any: ...

class _ByteMapView:
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    def __contains__(self, arg0: str) -> bool: ...
    def __delitem__(self, arg0: str) -> None: ...
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: str) -> bytes: ...
    def __iter__(self) -> typing.Any: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: str, arg1: typing.Any) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> dict: ...
    def get(
        self, key: str, default: typing.Any | None = None
    ) -> typing.Any: ...
    def items(self) -> typing.Any: ...
    def keys(self) -> typing.Any: ...
    def update(self, arg0: typing.Any) -> None: ...
    def values(self) -> typing.Any: ...

class _NodeFragmentVectorView:
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    def __bool__(self) -> bool: ...
    def __contains__(self, arg0: NodeFragment) -> bool: ...

    @typing.overload
    def __delitem__(self, arg0: typing.SupportsInt) -> None: ...
    @typing.overload
    def __delitem__(self, arg0: slice) -> None: ...

    def __eq__(self, arg0: object) -> bool: ...

    @typing.overload
    def __getitem__(self, arg0: typing.SupportsInt) -> NodeFragment: ...
    @typing.overload
    def __getitem__(self, arg0: slice) -> list: ...

    def __iter__(self) -> collections.abc.Iterator[NodeFragment]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

    @typing.overload
    def __setitem__(
        self, arg0: typing.SupportsInt, arg1: NodeFragment
    ) -> None: ...
    @typing.overload
    def __setitem__(self, arg0: slice, arg1: typing.Any) -> None: ...

    def append(self, arg0: NodeFragment) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> list: ...
    def count(self, arg0: NodeFragment) -> int: ...
    def extend(self, arg0: typing.Any) -> None: ...
    def index(self, arg0: NodeFragment) -> int: ...
    def insert(self, arg0: typing.SupportsInt, arg1: NodeFragment) -> None: ...
    def pop(self, index: typing.SupportsInt = -1) -> NodeFragment: ...
    def remove(self, arg0: NodeFragment) -> None: ...
    def reverse(self) -> None: ...

class _PortVectorView:
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    def __bool__(self) -> bool: ...
    def __contains__(self, arg0: Port) -> bool: ...

    @typing.overload
    def __delitem__(self, arg0: typing.SupportsInt) -> None: ...
    @typing.overload
    def __delitem__(self, arg0: slice) -> None: ...

    def __eq__(self, arg0: object) -> bool: ...

    @typing.overload
    def __getitem__(self, arg0: typing.SupportsInt) -> Port: ...
    @typing.overload
    def __getitem__(self, arg0: slice) -> list: ...

    def __iter__(self) -> collections.abc.Iterator[Port]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

    @typing.overload
    def __setitem__(self, arg0: typing.SupportsInt, arg1: Port) -> None: ...
    @typing.overload
    def __setitem__(self, arg0: slice, arg1: typing.Any) -> None: ...

    def append(self, arg0: Port) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> list: ...
    def count(self, arg0: Port) -> int: ...
    def extend(self, arg0: typing.Any) -> None: ...
    def index(self, arg0: Port) -> int: ...
    def insert(self, arg0: typing.SupportsInt, arg1: Port) -> None: ...
    def pop(self, index: typing.SupportsInt = -1) -> Port: ...
    def remove(self, arg0: Port) -> None: ...
    def reverse(self) -> None: ...

class _StringSchemaMapView:
    __hash__: None = None  # pyright: ignore[reportIncompatibleMethodOverride]
    def __bool__(self) -> bool: ...
    def __contains__(self, arg0: str) -> bool: ...
    def __delitem__(self, arg0: str) -> None: ...
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: str) -> str: ...
    def __iter__(self) -> typing.Any: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: str, arg1: typing.Any) -> None: ...
    def clear(self) -> None: ...
    def copy(self) -> dict: ...
    def get(
        self, key: str, default: typing.Any | None = None
    ) -> typing.Any: ...
    def items(self) -> typing.Any: ...
    def keys(self) -> typing.Any: ...
    def update(self, arg0: typing.Any) -> None: ...
    def values(self) -> typing.Any: ...

def create_in_process_wire_stream_pair(
    options: WireStreamOptions | None = None,
    first_options: WireStreamOptions | None = None,
    second_options: WireStreamOptions | None = None,
) -> tuple[InProcessWireStream, InProcessWireStream]: ...
def get_http_header(arg0: typing.Any, arg1: str) -> typing.Any: ...
def is_half_close_message(arg0: WireMessage) -> bool: ...
def is_status_chunk(arg0: Chunk) -> bool: ...
def make_half_close_message(trailers: typing.Any = {}) -> WireMessage: ...
def normalize_session_headers(headers: typing.Any | None = None) -> dict: ...
def status_code_from_http(arg0: typing.SupportsInt) -> int: ...
def status_code_from_websocket(arg0: typing.SupportsInt) -> int: ...
def status_code_to_http(arg0: typing.SupportsInt) -> int: ...
def status_code_to_websocket(arg0: typing.SupportsInt) -> int: ...
def status_from_chunk(arg0: Chunk) -> typing.Any: ...
def status_to_chunk(arg0: typing.Any) -> Chunk: ...
def validate_http_headers(arg0: typing.Any) -> None: ...
def validate_name_string(arg0: str) -> str: ...

ACCEPT: StreamMode
ACTION_DISPATCH_STATUS_OUTPUT: str = "__dispatch_status__"
ACTION_HEADER_PREFIX: str = "x-a11-"
ACTION_STATUS_MIMETYPE: str = "application/x-a11-status"
ACTION_STATUS_OUTPUT: str = "__status__"
CANCEL_ACTION_HEADER: str = "__action"
CANCEL_ACTION_NAME: str = "__cancel__"
CANDIDATE: SignallingMessageType
DEFAULT_MAX_CONCURRENT_NESTED_ACTIONS: int = 64
DEFAULT_SSE_CONNECT_ENDPOINT: str = "/connect"
DEFAULT_SSE_MESSAGE_ENDPOINT: str = "/streams/{id}/message"
DESCRIPTION: SignallingMessageType
EMPTY_WIRE_MESSAGE_SIZE: int = 4
ERROR: SignallingMessageType
JSON_MIMETYPE: str = "application/json"
MAX_SINGLE_MESSAGE_SIZE: int = 33554432
MSGPACK_MIMETYPE: str = "application/x-msgpack"
SESSION_MAX_SINGLE_MESSAGE_SIZE: int = 33554432
SESSION_STATUS_HEADER: str = "x-a11-session-status"
SSE_HTTP_HEADER_PREFIX: str = "x-a11-http-"
SSE_STREAM_ID_HEADER: str = "x-a11-stream-id"
START: StreamMode
TCP: TurnRelayType
TLS: TurnRelayType
UDP: TurnRelayType
WHOLE_JSON: str = "$"
WIRE_MESSAGE_VERSION: int = 1
WIRE_STREAM_ABORT_STATUS_HEADER: str = "x-a11-abort-status"
WIRE_STREAM_MAX_SINGLE_MESSAGE_SIZE: int = 33554432
__version__: str = "0.1.0"
HttpSseWireStreamServer = HttpSseServer
